package com.wootion.cast.vehcert.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class Hegeparam implements Serializable{
    private Long id;
    private String cateCode;
    private String vehClztxx;
    private String vehClzzqymc;
    private String vehCllx;
    private String vehClmc;
    private String vehClpp;
    private String vehClxh;
    private String vehDpxh;
    private String vehDpid;
    private String vehClsbdh;
    private String vehCjh;
    private String vehFdjxh;
    private String vehRlzl;
    private String vehPfbz;
    private String vehPl;
    private String vehGl;
    private String vehZxxs;
    private String vehQlj;
    private String vehHlj;
    private String vehLts;
    private String vehLtgg;
    private String vehGbthps;
    private String vehZj;
    private String vehZh;
    private String vehZs;
    private String vehWkc;
    private String vehWkk;
    private String vehWkg;
    private String vehHxnbc;
    private String vehHxnbk;
    private String vehHxnbg;
    private String vehZzl;
    private String vehEdzzl;
    private String vehZbzl;
    private String vehZzllyxs;
    private String vehZqyzzl;
    private String vehEdzk;
    private String vehBgcazzdyxzzl;
    private String vehJsszcrs;
    private String vehQzdfs;
    private String vehHzdfs;
    private String vehQzdczfs;
    private String vehHzdczfs;
    private String vehZgcs;
    private String vehBz;
    private String vehQybz;
    private String vehZxzs;
    private String vehYh;
    private String vehCddbj;
    private String vehClscdwmc;
    private String vehCsys;
    private String vehCpggh;
    private String vehPzxlh;
    private String vehGgpc;
    private String vehGgsxrq;
    private String isprototype;
    private String factory;
    private String ispass;
    private String carType;
    private String jfpzid;
}
